server=$1
port=$2
echo "RESURS: KORISNICI"
echo "POST - ispravno"
echo ""
curl -X POST "http://$server:$port/api/korisnici/" -H 'Content-Type: application/json' -d '{"ime":"Test", "prezime":"Test", "email":"test3@foi.unizg.hr", "korisnicko_ime":"ttest", "lozinka":"123456", "spol":"M", "adresa":"negdje 12", "telefon":"123"}'
echo ""
echo "POST - korime nije jedinstveno" 
echo ""
curl -X POST "http://$server:$port/api/korisnici/" -H 'Content-Type: application/json' -d '{"ime":"admin", "prezime":"Test", "email":"test3@foi.unizg.hr", "korisnicko_ime":"admin", "lozinka":"rwa", "spol":"M", "adresa":"negdje 12", "telefon":"123"}'
echo ""
echo "POST - fale neki podaci"
echo ""
curl -X POST "http://$server:$port/api/korisnici/" -H 'Content-Type: application/json' -d '{"ime":"", "prezime":"Test", "email":"", "korisnicko_ime":"tessssst", "lozinka":"123456", "spol":"M", "adresa":"negdje 12", "telefon":"123"}'
echo ""
echo "RESURS : korisnik/:korime"
echo "GET - sve u redu"
curl -X GET "http://$server:$port/api/korisnik/admin"
echo ""
echo "GET - fali korime/nepostojeći korisnik"
curl -X GET "http://$server:$port/api/korisnik/admins"
echo ""
echo "RESURS : uloga/:uloga_id"
echo "GET - sve u redu"
curl -X GET "http://$server:$port/api/uloga/3"
echo ""
echo "GET - nepostojeća"
curl -X GET "http://$server:$port/api/uloga/32"
echo ""
echo "RESURS : korisnici/prijava/:korime"
echo "POST - kriva lozinka"
echo ""
curl -X POST "http://$server:$port/api/korisnici/prijava/admin" -H 'Content-Type: application/json' -d '{"lozinka":"rwas"}'
echo ""
echo "POST - sve u redu"
echo ""
curl -X POST "http://$server:$port/api/korisnici/prijava/admin" -H 'Content-Type: application/json' -d '{"lozinka":"rwa"}'
echo ""
echo "POST - nepostojece korime"
echo ""
curl -X POST "http://$server:$port/api/korisnici/prijava/admins" -H 'Content-Type: application/json' -d '{"lozinka":"rwa"}'
echo ""
echo "POST - bez korisnickog imena"
echo ""
curl -X POST "http://$server:$port/api/korisnici/prijava/" -H 'Content-Type: application/json' -d '{"lozinka":"rwa"}'
echo ""
echo "RESURS : odjava"
echo "GET"
echo ""
curl -X GET "http://$server:$port/api/odjava"
echo ""
echo "RESURS : aktivacija"
echo "GET - sve u redu"
curl -X GET "http://$server:$port/api/aktivacija?korime=lmiha&kod=39512"
echo ""
echo "GET - fali podatak"
curl -X GET "http://$server:$port/api/aktivacija?korime=lmiha"
echo ""
echo "GET - kod i korime se ne podudaraju"
curl -X GET "http://$server:$port/api/aktivacija?korime=lmiha&kod=49512"
echo ""
echo "RESURS : javneKolekcije"
echo "GET"
echo ""
curl -X GET "http://$server:$port/api/javneKolekcije"
echo ""
echo "RESURS : javni sadržaji"
echo "GET - sve u redu"
echo ""
curl -X GET "http://$server:$port/api/javniSadrzaji/1"
echo ""
echo "GET - nedostaje kolekcija"
echo ""
curl -X GET "http://$server:$port/api/javniSadrzaji/"
echo ""
echo "RESURS : dohvat poveznice videa sadrzaja"
echo "GET - sve u redu"
echo ""
curl -X GET "http://$server:$port/api/film/video?id=391"
echo ""
echo "GET - fali id filma"
curl -X GET "http://$server:$port/api/film/video"
echo ""